export const ALL_INVENT_REQUEST = "ALL_INVENT_REQUEST";
export const ALL_INVENT_SUCCESS = "ALL_INVENT_SUCCESS";
export const ALL_INVENT_FAIL = "ALL_INVENT_FAIL";

export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST";
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS";
export const ALL_REVIEWS_FAIL = "ALL_REVIEWS_FAIL";

export const CLEAR_ERRORS = "CLEAR ERRORS";
