export const ALL_INVENT_REQUEST = "ALL_INVENT_REQUEST";
export const ALL_INVENT_SUCCESS = "ALL_INVENT_SUCCESS";
export const ALL_INVENT_FAIL = "ALL_INVENT_FAIL";

export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST";
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS";
export const ALL_REVIEWS_FAIL = "ALL_REVIEWS_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CREATE_INVENT_REQUEST = "CREATE_INVENT_REQUEST";
export const CREATE_INVENT_SUCCESS = "CREATE_INVENT_SUCCESS";
export const CREATE_INVENT_FAIL = "CREATE_INVENT_FAIL";
export const CREATE_INVENT_RESET = "CREATE_INVENT_RESET";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";
export const ADD_CART_RESET = "ADD_CART_RESET";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const CLEAR_ERRORS = "CLEAR ERRORS";
